### ISSUE TITLE
ombi not syncing with radarr

### ISSUE THREAD

**Issue by choldi** [linuxserver/docker-ombi#38]
ombi not working sending series to radarr.
Seems that ombi has been upgrade to solve that problem
https://github.com/tidusjar/Ombi/issues/2544

Ombi 
Version | 3.0.3919
Branch | master

Debian scratch 9.5

Docker-compose.yml
ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      TZ: 'Europe/Madrid'
    restart: unless-stopped
    volumes:
      - ./config/ombi:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Madrid
      - PGID=0
      - PUID=0

2018-10-19 20:38:15.435 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.ImagesController.GetTvBanner(Int32 tvdbid) in C:\projects\requestplex\src\Ombi\Controllers\ImagesController.cs:line 42
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24

**Comment by j0nnymoe** [comment]
are you using our latest image?

**Comment by choldi** [comment]
I think so.
I have this in my docker-compose.yml file

ombi:
image: linuxserver/ombi:latest

**Comment by j0nnymoe** [comment]
run this command and post the output `docker inspect -f '{{ index .Config.Labels "build_version" }}' ombi`

**Comment by choldi** [comment]
#docker inspect -f '{{ index .Config.Labels "build_version" }}' ombi
Linuxserver.io version:- 123 Build-date:- October-18-2018-07:14:01-UTC

**Comment by j0nnymoe** [comment]
You have the latest container then. Our ombi image is rebuilt every time tidusjar releases a new build.

**Comment by choldi** [comment]
OK, thanks. I'll ask in tidusjar ombi github
