### ISSUE TITLE
 i create a new ombi docker,it also cant work. but it can work fine before.

### ISSUE THREAD

**Issue by LB-DotFish** [linuxserver/docker-ombi#99]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

sometimes the watchtower docker update ombi,then it cant work.
i create a new ombi docker,it also cant work. but it can work fine before.
------------------------------

## Current Behavior

the discover has nothing, and the search also cant work.
the log and terminal constant produce bug.

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

synology 920+
DSM 7.1-42661 Update 1
INTEL Celeron J4125

## Docker logs

fail: Ombi.ErrorHandlingMiddleware[0]
Something bad happened, ErrorMiddleware caught this

2022-05-28 23:33:15.872 +08:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2022-05-28 23:33:15.971 +08:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2022-05-28 23:33:15.975 +08:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2022-05-28 23:33:15.977 +08:00 [Information] RAMJobStore initialized.
2022-05-28 23:33:15.981 +08:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2022-05-28 23:33:15.981 +08:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2022-05-28 23:33:15.981 +08:00 [Information] Quartz scheduler version: 3.1.0.0
2022-05-28 23:33:15.982 +08:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2022-05-28 23:33:16.099 +08:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2022-05-28 23:33:34.120 +08:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 40
   at Ombi.Api.FanartTv.FanartTvApi.GetMovieImages(String movieOrImdbId, String token) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.FanartTv/FanartTvApi.cs:line 42

**Comment by LB-DotFish** [comment]
its like the clash caused
